### PR TITLE
Update to refresh-token function

### PR DESCRIPTION
**Pull request by eraf2135**
refresh-token was throwing an ArityException because it wasn't sending nonce and timestamp to sig/oauth-params.  I also updated it to accept verifier code and sign the request with the same signature as the access-token request.

### CODE REVIEW

**Comment by camdez** [comment]
👍  `refresh-token` has been objectively broken since 28f68daf07f157f949fe3d7d87550734e0f5af22 (September 2012) when the 2-arity version of `oauth-params` was removed.

**Comment by mattrepl** [comment]
Thanks for the report. Can you please describe the issue?

**Comment by mattrepl** [comment]
Ah, didn’t see there was previous report. Will take a look. Thanks for bumping.

**Comment by camdez** [comment]
@mattrepl Invoke `refresh-token` with any valid parameters—you'll get an `ArityException` from [the call to `sig/oauth-params` on line 172](https://github.com/mattrepl/clj-oauth/blob/1d6634e276c380256cacf3f8eec5668c5b330b74/src/oauth/client.clj#L172) because it passes two arguments where at least three are required.

The rest of the changes appear to me to essentially maintain behavior while providing the necessary parameters to `sig/oauth-params` and refactoring a touch by leveraging `build-oauth-token-request` to generate the signature.

For the record, I haven't run this yet, but it looks sensible. I will probably be using it in the next day or two, so I can report back later if that's helpful.

**Comment by camdez** [comment]
Can now confirm that I'm able to successfully use this new implementation of `refresh-token`.

**Comment by mattrepl** [comment]
Ok, thanks for the update. Will merge, there may be a delay for release to clojars.

**Comment by camdez** [comment]
@mattrepl Fantastic. Thanks for taking the time to review and for the merge.

If there is a delay getting it to Clojars and anyone needs it sooner, there's an alternate version on Clojars at [`org.clojars.eraffoul/clj-oauth`](https://clojars.org/org.clojars.eraffoul/clj-oauth) (by the originator of this PR, @eraf2135) that is precisely this project at the current state of master.

**Comment by camdez** [comment]
Any chance of a new release soon? 🙏  I'd love to see this fix on Clojars so I can throw away my local hacks. Thanks!

**Pull request merged**
