### PR TITLE
Allow extra params when constructing user approval URI

### PR DESCRIPTION
**Pull request by danielsz**
Allow user to specify extra params when constructiing approval URI.
Specific use case is the "force_login" option in the Twitter authentication flow.

See #30

### CODE REVIEW

**Comment by mattrepl** [comment]
Hey, thanks for the patch. This is probably OK, but I need to load up context to do a quick sanity check before accepting. Swamped this evening, but will get to it soon.

**Comment by danielsz** [comment]
Yes, of course. Take your time. 
Thanks!

**Comment by mattrepl** [comment]
Thanks for the pull request!

**Comment by danielsz** [comment]
:+1: thank you!

**Pull request merged**
